apiVersion: v1
kind: Service
metadata:
  name: qr-val-service
  labels:
    app: qr-val-app
spec:
  selector:
    app: qr-val-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer